# Introducción a la Programacion con Python

En este notebook vamos a recorrer algunos conceptos básicos de programación en general y como los aplicamos con Python. 

Google es tu mejor amigo, usalo siempre que te trabes o quieras ampliar algún tema. La comunidad de usuarios de Python es enorme y muy activa, así que es muy muy probable que alguien haya contestado exactamente la duda que vos tenes (escribila de manera explicita en ingles en la barra del buscador). 

## 1. Variables, Tipos de Datos y Operaciones

### 1.1 Variables

Al crear una variable le estás poniendo un nombre a un objeto. Cada variable debe llevar un nombre a través del cual nos referimos a ella, los nombres deben ser únicos y, en lo posible, ser lo mas explícitos posibles para evitar confusiones. Usando el `=` se asigna un valor a una variable. No es un igual matemático/lógico, puedes pensarlo como una flecha (`<--`) que asigna lo que hay del lado derecho a lo que hay del lado izquierdo. Recordemos algunos ejemplos.


In [ ]:
# Asignamos el valor 3 a una variable que creamos, de nombre x
x = 3

# Evaluamos e imprimimos en pantalla el resultado
print(x)

In [ ]:
# Podemos definir una nueva variable como la suma de dos anteriores
z = x + y

print(z)

In [ ]:
# Se peude tambier asignar un valor de texto otra variable
un_texto = 'HOLA!'

print(un_texto)

In [ ]:
**Probar:** ejecutar la siguiente celda. ¿Cuál es la diferencia?

In [ ]:
print(un_texto)
print('un_texto')

### Nota importante:
Al correr esta ultima linea, deben ver un mensaje de error. Los mensajes de error son MUY IMPORTANTES. Nos brindan información muy valiosa cuando nuestro código no funciona. En este caso, nos está avisando que no puede imprimir la variable 'un_texto', ya que la eliminamos y no está definida.

### 1.2 Tipos de Datos
Cuando definimos una variable, dependiendo el contenido que le asignamos, la misma será de un determinado tipo. Los tipos de datos más comunes de variables son: `int`,`float`,`string` y `boolean`. Veamos algunos ejemplos de cada tipo.

In [ ]:
a = 42
print(type(a))

<class 'int'>


In [ ]:
b = 7.8
print(type(b))

<class 'float'>


In [ ]:
c = True
print(type(c))

<class 'bool'>


In [ ]:
t1 = 'hola'
print(type("hola"))

t2 = '523'
print(type('t2'))

<class 'str'>
<class 'str'>


**Nota**: a pesar de ser un número, la variable `t2` es de tipo `string`. Esto se debe a que lo pusimos entre comillas.

In [ ]:
# Este es un tipo especial de variable, que se utiliza para simbolizar algo 'vacio'
d = None
print(type(d))

<class 'NoneType'>


Si por algun motivo (ya veremos que esto es algo que suele suceder), uno desea explicitar el tipo de variable y no dejar que python lo asuma por si solo, esto también es posible.

In [ ]:
numero = 45
print(type(numero))

# Quiero que sea un 'float' y no un int
numero = float(45)
print(type(numero))

# Quiero que sea un 'string' y no un int
numero = str(45)
print(type(numero))

<class 'int'>
<class 'float'>
<class 'str'>


In [ ]:
otro_numero = 45.0
print(type(otro_numero))

# Quiero que sea un 'int' y no un 'float'
otro_numero = int(45.0)
print(type(otro_numero))

<class 'float'>
<class 'int'>


**Ejercicio**: Cambiar el tipo de la variable 'numero' a float.

In [ ]:
numero = '5'
numero = float(numero)

# La siguientes lineas de codigo chequean si hiciste correctamente el ejercicio
# No importa si no entiendes qué hace.
if type(numero) is float:
    print('Correcto!')
else:
    print('Convierte la variable a tipo float')

Correcto!


### 1.3 Operaciones
Con las variables que definimos, podemos realizar distintas operaciones. Dependiendo el tipo de variable, hay diferentes operaciones diponibles.



#### 1.3.1 Operaciones con números

Se pueden realizar las operaciones basicas entre numeros

In [ ]:
a = 20
b = 4
print(a+b)
print(a-b)

24
16


Se pueden realizar las operaciones incluso entre distintos tipos de variables

In [ ]:
a = 20
b = 4.5

c = a+b
d = a-b

print(c)
print(d)

24.5
15.5


¿De qué tipo es la variable resultante? Trata de adivinarlo antes de correr la celda siguiente.

In [ ]:
print(type(c))
print(type(d))

<class 'float'>
<class 'float'>


También podemos dividir números.

In [ ]:
x = 10
y = 3
z = x/y
print(z)

3.3333333333333335


¿De qué tipo es la variable resultante de hacer la división? A pesar de dividir dos números enteros, el resultado es de tipo `float`. ¡Ésta es una de las diferencias entre Python 2 y Python 3.

In [ ]:
print(type(z))

<class 'float'>


La siguiente operación es muy usada en computación, nos devuelve el resto de la división. ¿No recuerdas qué es el resto? Puedes investigarlo [aquí](https://www.disfrutalasmatematicas.com/numeros/division-resto.html).

In [ ]:
x = 10
y = 3
print(x%y)
print(type(x%y))

1
<class 'int'>


**Ejercicio**: Calcular el porcentaje que representa el valor 17 sobre un total de 54 y guardarlo en una variable llamada `porcentaje`.

porcentaje = 17*100/54
print(porcentaje)

#### Operaciones con Texto

In [ ]:
txt_1 = 'Los textos'
txt_2 = ' se concatenan.'
print(txt_1 + txt_2)

Los textos se concatenan.


In [ ]:
txt_3 = 'Los textos se multiplican. '
print(txt_3 * 2)

Los textos se multiplican. Los textos se multiplican. 


In [ ]:
b = 'Los textos'
c = ' no se restan.'
print(b - c)

TypeError: ignored

Nota: No nos cansaremos de decirles que presten atención a los mensajes de error.

In [ ]:
# Que pasa si queremos sumar un número al texto?
b = 'Mi edad es '
c = 28
print(b + c)

El error nos dice que a los 'string' solo se le pueden concatenar otros 'strings' (no enteros). La manera correcta sería entonces:

In [ ]:
# Que pasa si queremos sumar un número al texto?
b = 'Mi edad es '
c = 28
print(b + str(c))

Ejercicio: Armar la frase 'El gran gran gran gran gran castillo mide 50 metros.' a partir de operar con las siguientes variables:

In [ ]:
txt1 = 'gran '
txt2 = 'El '
tet3 = 'mide '
txt4 = ' metros.'
numero = 50

frase = COMPLETAR




#### 1.3.3 Operaciones Lógicas

In [ ]:
variable_1 = True
variable_2 = False
print(variable_1 or variable_2)

True


In [ ]:
print(not(variable_1))

False


In [ ]:
variable_3 = variable_1 and variable_2
print(variable_3)

False


## 2. Listas, Loops y Condicionales



### 2.1 Listas

Son un objeto central en el lenguaje Python. Estan compuestas por una sucesión de objetos en un orden determinado. Se definen mediante corchetes '[ ]', y los objetos dentro de ellas se separan por comas ','.

In [ ]:
lista_1 = [42, 4.7, True, 'Texto']
print(lista_1)

[42, 4.7, True, 'Texto']


In [ ]:
# Podemos inspeccionar el largo de una lista, o sea, su cantidad de elementos
len(lista_1)

4

Podemos inspeccionar elementos de una lista accediendo a una determinada posición de la misma. Los indices de las posiciones empiezan en 0, y se especifican poniendo corchetes con el indice adentro luego del nombre de la lista:

In [ ]:
print(lista_1[0])
print(type(lista_1[0]))

42
<class 'int'>


In [ ]:
print(lista_1[3])
print(type(lista_1[3]))

Texto
<class 'str'>


In [ ]:
print(lista_1[2])
print(type(lista_1[2]))

True
<class 'bool'>


In [ ]:
# Tambien podemos selecciona una porción de lista
#(ya veremos esto en detalle mas adelante)
print(lista_1[0:3])

[42, 4.7, True]


In [ ]:
# Definimos una segunda lista
lista_2 = [0, lista_1, 'Mas texto']
print(lista_2)
print(len(lista_2))

[0, [42, 4.7, True, 'Texto'], 'Mas texto']
3


Notemos que en esta segunda lista, agregamos dentro la primera. Toda la primer lista cuenta como un único elemento.

In [ ]:
# Un elemento de la lista_2 es la lista_1
print(lista_2[1])

[42, 4.7, True, 'Texto']


Podemos crear listas vacias, e ir agregándole elementos con el método 'append()'

In [ ]:
lista_vacia = []
len(lista_vacia)

0

In [ ]:
lista_vacia.append(42)
lista_vacia.append('un segundo item')
print(lista_vacia)
print(len(lista_vacia))

[42, 'un segundo item', 42, 'un segundo item', 42, 'un segundo item']
6


Prueben que pasa si corren nuevamente la celda anterior (justo arriba de esta).

Ejercicio: Defina una lista vacia llamada 'lista_nueva' y agreguele los elementos a, b y c.

In [ ]:
a = 8
b = 'world'
c = [12,24.5,66]

lista_nueva = COMPLETAR

### 2.2 Loops
Los Loops son estructuras de codigo fundamentales en cualquier lenguaje de programación. Son bloques de código que se repiten dada una cierta cantidad de veces dada condición.


#### 2.2.1 For
El For es un loop en el que un bloque de código se repite tantas veces como elementos haya en una determinada lista. En cada iteración (repetición) hay una variable que va tomando el valor de uno de los elementos en esta lista.

In [ ]:
lista_numeros = [3,55,1,876,12]

# Definimos el codigo dentro del for mediante la indentación
# (Todo lo qu este corrido un 'tab' a la derecha)
for elemento in lista_numeros:
    print(elemento)

3
55
1
876
12


In [ ]:
# Repitamos los mismo que la celda anteriro
# pero ahora agregemos una variable i 
# que cuente la cantidad de veces que ese corre el codigo 

lista_numeros = [3,55,1,876,12]

# La iniciamos en cero
i = 0

for elemento in lista_numeros:
    
    # Le sumamos 1 cada vez que entra
    i = i+1
    print(elemento)

3
55
1
876
12


In [ ]:
print(i)

5


También podemos recorrer listas de texto. Presten atencion al siguiente codigo, e intenten precedir el resultado antes de correr la celda.

In [ ]:
lista_nombres = ['Ernesto', 'Camilo', 'Violeta']
nueva_lista = []

for item in lista_nombres:
    oracion = 'Mi nombre es ' + item
    nueva_lista.append(oracion)

# Este print esta fuera del for, no está indentado
print(nueva_lista)

['Mi nombre es Ernesto', 'Mi nombre es Camilo', 'Mi nombre es Violeta']


Ejercicio: Genere una lista llamada 'numerotes' que contenga el cuadrado de cada elemento en la lista 'numeritos'.

In [ ]:
numeritos = [3,1,5,7,12,10,17,4,22]

numerotes = COMPLETAR

for COMPLETAR

#### 2.2.2 While
El while repite un bloque de código mientras se cumpla una cierta condición que le ponemos. Para mayor claridad, pondremos la condición dentro de parentesis '()'.

In [ ]:
numero = 1

while (numero < 5):
    print(numero)
    numero = numero + 1

1
2
3
4


In [ ]:
# La condición debe ser una operación lógica y dar como resultado un booleano
print(2 < 5)
type(2 < 5)

True


bool

In [ ]:
print(5 < 5)
type(5 < 5)

False


bool

Ejercicio: Decida si quiere ejecutar el siguiente bloque de código.

In [ ]:
numero = 1

while (numero > 0):
    numero = numero + 1

KeyboardInterrupt: 

Si decidió ejecutarlo (o corrió la celda antes de leer la consigna), felicitaciones usted ha colgado por primera vez un programa! Pero como ya dijimos, hay que probar y equivocarse, nada es irreversible. Vaya a la solapa 'Kernel' del menú y seleccione 'Interrupt'. Lo que sucuede es que la condición del wihle será siempre cierta, por ende nuestro programa se quedará repitiendo el bloque de codigo dentro del loop indefinidamente. Puedeaveriguar cuantas iteraciones realizo la maquina inspeccionando la variable 'numero':

In [ ]:
print(numero)

### 2.3 Condicionales
Los condicionales son un bloque de codigo que se ejecuta solo en el caso que se cumpla una dada condición.



#### 2.3.1 If
El condicional mas simple es el if. Nuevamente para mayor claridad escribiremos la condicion entre parentesis (), esto no es enecesario.

In [ ]:
valor = 15

if (valor > 10):
    print('El valor el mayo que 10')

La condición que escribimos debe ser una operación lógica que da como resultado un booleano.

In [ ]:
print(15 > 10)

True


In [ ]:
print(type(15 > 10))

<class 'bool'>


#### 2.3.2 If, Else
A este condicional se le peude agregar otro bloque de codigo que se ejecute si la condición exigida NO se cuemple. Esto se logra mediante la expresión 'else'.

In [ ]:
nombre = 'Pedro'

if (nombre == 'Juan'):
    print('Esta persona se llama Juan')
else:
    print('Esta persona NO se llama Juan')

Esta persona NO se llama Juan


In [ ]:
'Juan'=='Pedro'

False

#### 2.3.3 If, Elif, Else
A esta estructura se le pueden sumar tantas condiciones encadenadas como uno desée, mediante la expresión 'elif'. El orden en que se van chequeando las condiciones depende de su posición, priemero se chequea el 'if, luego el primer 'elif' luego el segundo y así sucesivamente.

In [ ]:
edad = 20

if (edad < 18):
    print('Esta persona tiene menos de 18 años')
elif (edad > 18):
    print('Esta persona tiene mas de 18 años')
else:
    print('Esta persona tiene justo 18 años')

Esta persona tiene mas de 18 años


Ejercicio: Escriba un bloque de código que, dado un número, imprimar la frase 'El numero es par' si el número es par o la frase 'El numero es impar' si no lo es.

In [ ]:
numero = 17

if COMPLETAR:
    print(COMPLETAR)
else COMPLETAR:
    print(COMPLETAR)

### 2.4 Combinando estructuras de código
Las estructuras de loops y condicionales que aprendimos se peuden combinar para generar comportamientos mas complejos.

In [ ]:
lista_de_edades = [4,20,15,29,11,42,10,18]
lista_mayores = []

# Queremos armar una lista solo con las edades mayores o iguales a 18
for edad in lista_de_edades:
    if (edad >= 18):
        # Agremos a la lista de mayores
        lista_mayores.append(edad)

print(lista_mayores)

[20, 29, 42, 18]


## 3. Numpy

Numpy es una libreria que permite el manejo de vectores y matrices en Python. Es por lejos la librería de Python mas usada y es escencial para la mayoría de las tareas, ya que muchas otras librerias de Python dependen de esta. 

A la hora de trbajar con una nueva librería, es muy importante que googlees y consultes la [documentación](https://numpy.org/doc/1.19/).

Cuando queremos usar una librería, primero debemos importarla. Esto nos permite usar todas las funcionalidades que esa librería ofrece (funciones y objetos). Al importar una libreria elegimmos un nombre (o shorcut) por el cual llamarla, a Numpy se la suele apodar `np`:

In [ ]:
import numpy as np

Numpy trabaja con un tipo de objetos llamados `arrays`. Son similares las listas, pero estos pueden contener únicamente elementos numéricos y de un mismo tipo. Podemos crear un array a partir de una lista: 

In [ ]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Los `arrays` se comportan en muchos sentidos de manera similar a la de un vector algebraico. 

Por ejemplo, podemos realizar varios tipos de operaciones elelmento a elemento sobre el vector:

In [ ]:
print(arreglo + 1)
print(arreglo - 2)
print(arreglo*4)
print(arreglo**2)

[1 2 3 4 5 6]
[-2 -1  0  1  2  3]
[ 0  4  8 12 16 20]
[ 0  1  4  9 16 25]


Los `arrays` no solo pueden crearse a partir de listas, también existen varias funciones que facilitan la creación de algunos que se usan con frecuencia. 

Dejamos a continuación algunas de estas fucniones de creación de `arrays` para que explores lo que hacen. Ademas de consultar la documentación de la librería, podes apretar `shift` + `tab` para que te aparezca la ayuda de la función que estás escribiendo (esto suele ser muy cómodo).

In [ ]:
arreglo = np.arange(3,20,2)
print(arreglo)

In [ ]:
arreglo = np.linspace(1,10,3)
print(arreglo)

[ 1.   5.5 10. ]


In [ ]:
arreglo = np.ones(10)
print(arreglo)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
arreglo = np.zeros(3)
print(arreglo)

[0. 0. 0.]


Los `arrays` puede tener mas de una dimensión, esto es equivalente a pensar matrices en vez de vectores. A continuacion vamos a crear un `array` con 2 filas y 4 columnas:

In [ ]:
arreglo_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arreglo_2d)

[[1 2 3 4]
 [5 6 7 8]]


Si queremos averiguar la cantidad de filas y columnas en uno arreglo de numpy, podemos usar el atributo shape del arreglo: 

In [ ]:
print(arreglo_2d.shape)

(2, 4)


Otro ejemplo de 3 filas y 2 columnas seríá:


In [ ]:
arreglo_2d = np.array([[1,2],[3,4],[5,6]])
print(arreglo_2d)
print(arreglo_2d.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


El atributo size nos dice cuantos elementos posee en total un `array`:

In [ ]:
print(arreglo_2d.size)

6


Un término importante para aprender es el de *slicing*. Este se refiere a la manera de acceder a cierto grupo de filas o columnas en un dado `array`. Vamos a dejales las siguiente celdas para que exploren

In [ ]:
arreglo_2d = np.arange(9).reshape(3,3)
print(arreglo_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print(arreglo_2d[1,:])
# print(arreglo_2d[1,2])
# print(arreglo_2d[:,0])
# print(arreglo_2d[0:2,:])
# print(arreglo_2d[0:1,0:1])

[3 4 5]


Por ultimo te dejamos algunas funciones que operan sobre `arrays` para que explores su funcionamiento.

**Observación**: notar que muchas funcionalidades se puede escribir equivalentemente como `np.una_funcion(arreglo)` o `arreglo.una_funcion()`. En programación le decimos *función* en el primer caso y *método* en el segundo. Pero no se preocupen, con ambas maneras de escribirlas obtendrán los mismo resultados.

In [ ]:
un_arreglo = np.array([-200,2,5,17,1,95])
print(un_arreglo.min())
print(un_arreglo.max())

-200
95


In [ ]:
print(np.min(un_arreglo))
print(np.max(un_arreglo))

95
-200


In [ ]:
# # Prueba ir descomentando y viendo que hacen estas celdas
# arreglo = np.arange(9)
# print(arreglo)
# np.random.shuffle(arreglo)
# print(arreglo)
# arreglo = arreglo.reshape((3,3))
# print(arreglo)

[0 1 2 3 4 5 6 7 8]
[1 0 4 7 8 6 3 2 5]
[[1 0 4]
 [7 8 6]
 [3 2 5]]


In [ ]:
# print(arreglo.max())
# print(arreglo.max(axis = 0))
# print(arreglo.max(axis = 1))